# This is a basic workflow to help you get started with Actions

name: Dry Run of FOIAs


# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        
      - name: install requirements
        run: |
          pip install .

      - name: preview FOIAs
        run: foia_send forest_requests/*.md miriam_requests/*.md -n
